### ISSUE TITLE
Test integration

### ISSUE THREAD

**Issue by Amedeo91** [enricodeleo/fattura24#2]
Hello,

I would like to use this module to integrate the API exposed by Fattura24.

I was wondering if there is some sandbox that can be used in order to test the integration.

Regards,
Amedeo

**Comment by enricodeleo** [comment]
@Amedeo91 As far as I know, there isn't one. By the way, I'm not related to fattura24 (although this module is recognized by them it has been developed independently), so they may have internal plans I am not aware of.
