### ISSUE TITLE
Aggiunta di più Row

### ISSUE THREAD

**Issue by waliente** [enricodeleo/fattura24#3]
Ciao, seguendo la documentazione sul readme nell'array Rows bisogna aggiungere degli oggetti con chiave Row... ma così facendo gli oggetti con la stessa chiave finiscono per sovrascriversi ed avere un solo oggetto con chiave Row nell'array Rows. 

Example: 

`fattura_24_data.Rows.push(
        {
          Row: {
            Description: ``,
            Qty: 1,
            Price: xxx_amount,
            VatCode: tax.value,
            VatDescription: tax.value + '%'
          },
          Row: {
            Description: ``,
            Qty: 1,
            Price: yyy_amount,
            VatCode: 0,
            VatDescription: '0%',
            FeVatNature: 'N4'
          }
        }
      );`

Mentre se invece vado ad inserire più Rows in questo modo: 

`fattura_24_data.Rows.push(
        {
          Row: {
            Description: ``,
            Qty: 1,
            Price: xxx_amount,
            VatCode: tax.value,
            VatDescription: tax.value + '%'
          },
        },
        {
          Row: {
            Description: ``,
            Qty: 1,
            Price: yyy_amount,
            VatCode: 0,
            VatDescription: '0%',
            FeVatNature: 'N4'
          }
        }
      );`

Alla fine otterrò l'xml:

`<Rows>
         <Row>
            <Description></Description>
            <Qty>1</Qty>
            <Price>0.46</Price>
            <VatCode>22</VatCode>
            <VatDescription>22%</VatDescription>
         </Row>
      </Rows>
      <Rows>
         <Row>
            <Description></Description>
            <Qty>1</Qty>
            <Price>5.6</Price>
            <VatCode>0</VatCode>
            <VatDescription>0%</VatDescription>
            <FeVatNature>N4</FeVatNature>
         </Row>
      </Rows>`

Che differisce con l'xml presente su https://www.fattura24.com/api-documentazione/ relativo alla fattura elettronica. 

Qualche suggerimento?

**Comment by enricodeleo** [comment]
Ciao @waliente! Rows deve essere un array di oggetti, credo ci sia un errore nel tuo primo snippet, nel quale manca un `{` prima del secondo `Row`.

Riscrivo lo snippet qui nel modo corretto, per chiarezza:

```js
fattura_24_data.Rows.push(
  {
    Row: {
      Description: ``, 
      Qty: 1, 
      Price: xxx_amount, 
      VatCode: tax.value, 
      VatDescription: tax.value + '%',
    },
  },
  {
    Row: { 
      Description: ``, 
      Qty: 1, 
      Price: yyy_amount, 
      VatCode: 0, 
      VatDescription: '0%',
      FeVatNature: 'N4',
    },
  },
);
```

**Comment by waliente** [comment]
Ok grazie Enrico. 

Così facendo ho notato che ottengo però l'xml così:


<Rows>
  <Row>
   ...
  <Row>
</Rows>
<Rows>
  <Row>
   ...
  <Row>
</Rows>

Che differisce con quanto riportato sulla documentazione del sito di fattura 24. Ad ogni modo seguirò questa linea, grazie ;)

**Comment by enricodeleo** [comment]
Fammi sapere se l'operazione va a buon fine e vedi le fatture correttamente visualizzate sulla tua dashboard fattura24

**Comment by waliente** [comment]
Allora sulla dashboard si le vedo correttamente suddivise in due campi diciamo. 

Purtroppo però mi risponde sempre returnCode: '-2' dicendomi che il mio XML è sbagliato. 

Ma c'è un modo per sapere quali campi sono errati?

Grazie per il supporto.

**Comment by enricodeleo** [comment]
Guarda ho avuto lo stesso problema con le fatture elettroniche, mentre invece nessun problema con le fatture tradizionali. Non ho nessuna relazione con Fattura24 per cui l'unica cosa che ho potuto fare è segnalare loro la questione.

**Comment by waliente** [comment]
Idem con patate :D 

Anche a me sta dando problemi con il documentType: 'FE', mentre con quelle tradizionali no problem.

Mi risponde sempre che l'xml è errato. Mi consigli di scrivere al loro supporto?

**Comment by enricodeleo** [comment]
Proprio oggi ho fatto un altro test ed è andato a buon fine anche con FE per questo pensavo avessero risolto. Sì ti direi di scrivere, magari capiamo meglio.

**Comment by waliente** [comment]
Ciao Enrico, 

volevo segnalarti che con la modalità:

```
fattura_24_data.Rows.push(
  {
    Row: {
      Description: ``, 
      Qty: 1, 
      Price: xxx_amount, 
      VatCode: tax.value, 
      VatDescription: tax.value + '%',
    },
  },
  {
    Row: { 
      Description: ``, 
      Qty: 1, 
      Price: yyy_amount, 
      VatCode: 0, 
      VatDescription: '0%',
      FeVatNature: 'N4',
    },
  },
);
```

adesso non mi visualizza più i prodotti sulla dashboard di fattura24, e ovviamente quando vado a fare la verifica dell'xml mi dice di aggiungere almeno un prodotto.

**Comment by enricodeleo** [comment]
Durant e i miei vari test, ho sempre utilizzato .map per processare i miei ordini e creare le row. Ad esempio (da un progetto reale)

```js
const orderRows = await Promise.all(orders.map(async (order) => {
      const elementExchangedCost = await currencyConversion(order.productCost || 0);
      const element = {
        Row: {
          Code: order.orderNumber,
          Description: { _cdata: `Payment for order ID ${order.orderNumber}` },
          Price: 59.99,
          VatCode: 0,
          Um: '',
          VatDescription: '0%- Non Imp. Art.7, bis D.P.R. 633/72',
          FeVatNature: 'N2',
          Qty: 1,
        },
      };

      return element;
}));

// [...] altre operazioni

const documentPayload = Object.assign({}, defaults, payament, customerData, { Rows: orderRows });

try {
      invoiced = await fattura24.saveDocument(documentPayload);
} catch (error) {
      return done(error);
}
```
