### ISSUE TITLE
How to use GetFile?

### ISSUE THREAD

**Issue by andrea-sdl** [enricodeleo/fattura24#5]
Hi there,

quick question:Is there a way to use getFile? 
Because it requires a GET Param (docId) with the document id we want to download.

I don't see how I can pass it to the fattura24 object, and the doc is missing an example, if you tell me how to do it I can provide a PR with the updated DOC if needed.

**Comment by andrea-sdl** [comment]
mmm, right now the code is quite generic, which is nice. 
Adding the second parameter as a string would require some special hardcoding for the getfile case, because you don't know how the query param is named (in this case "docId").

To be fair, the getFile method would still probably require some special handling since it returns a file instead of an xml, so it might be worth the exception.

Otherwise I'd consider changing the second object to a more generic object like
```
{
params:{}
body:{}
}
```

this can be made backwards compatible by searching the body attribute, if it's not there we're in the old behaviour and we should serialize the entire object as body, otherwise we can either have a body or not have it at all (for the GetFile).

This solution could be beneficial in the long term if we want, although I think that sooner or later fattura24 will redo the entire WS api to be more up to date.

**Comment by enricodeleo** [comment]
I tried to keep generic, see -> https://github.com/enricodeleo/fattura24/blob/master/src/fattura24.js#L163

It should work with current apis. Please check if it works for you and let me know!
